### PR TITLE
Multiples tests for the LPS-156875 to check the behavior on CI 

### PR DESCRIPTION
**Pull request by felipelorenz**

### CODE REVIEW

**Comment by felipelorenz** [comment]
ci:test:search:norebase

**Comment by gustavolimav** [comment]
ci:test:search:norebase

**Comment by gustavolimav** [comment]
ci:test:search:norebase

**Comment by gustavolimav** [comment]
ci:test:search:norebase

**Comment by felipelorenz** [comment]
ci:test:search:norebase

**Pull request closed without merging**
